title: For You For XJ 
author: maiqiang
email: mai_qiang@163.com
description: > # this means to ignore newlines until "baseurl:"
  i love you 
  you love me
  we are a happy family
theme: minima
# social links
twitter_username: no-one # DO NOT include the @ character, or else the build will fail!
github_username:  maiqiang1998 # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
